### ISSUE TITLE
Making *.txt

### ISSUE THREAD

**Issue by mnot** [martinthomson/i-d-template#251]
... should call xml2rfc with `--no-headers` and whatever other magic the RFC Editor uses, to reduce diffs.

**Comment by mnot** [comment]
`--no-pagination` that is.

**Comment by martinthomson** [comment]
You can configure xml2rfc to include that flag yourself, but then it applies to all invocations and overwrites the default configuration, but it does work (and the `--html` version doesn't choke).

e.g.,
```make
xml2rfc := xml2rfc --no-pagination

LIBDIR := lib
include $(LIBDIR)/main.mk
...
```

Does this make tools other than rfcdiff viable?  Because if that is the case, then it's probably a good option, at least by default (people who like page numbers can always override as shown).

**Comment by MikeBishop** [comment]
What about only adding these options when doing `make diff`?

**Comment by mnot** [comment]
The point is to have something to diff the RPC's output from...

**Comment by mnot** [comment]
@martinthomson yes, it does; I'm using FileMerge with good results.

**Comment by martinthomson** [comment]
Thanks @mnot.  This might be a thumb in the eye of those who want page numbers, but I think that your use case is more relevant in this case.
