### ISSUE TITLE
Archive Issues and Pull Requests workflow run failed for main branch

### ISSUE THREAD

**Issue by larseggert** [martinthomson/i-d-template#277]
Any idea why this is happening now? I see this in several repos, e.g., https://github.com/NTAP/rfc8312bis/runs/2385956744?check_suite_focus=true

**Comment by bemasc** [comment]
I see the same error with the older CircleCI integration too:
```
#!/bin/bash -eo pipefail
make artifacts CI_ARTIFACTS=/tmp/artifacts

mkdir -p /tmp/artifacts
git fetch -qf origin gh-pages:gh-pages
/usr/bin/python3: No module named archive-repo
make: *** [lib/archive.mk:25: archive.json] Error 1
```

**Comment by martinthomson** [comment]
We got a rash of these.  @MikeBishop made some changes here, but the docker image failed to build correctly (tools.ietf.org was down...yay).  This should eventually go away.

**Comment by martinthomson** [comment]
@MikeBishop, I've backed out #274 as a result of this.  It looks like this can likely be fixed by https://github.com/MikeBishop/archive-repo/issues/12, so I've left the Dockerfile changes in place for now.  Fixing it on this end will only take a rebuild of the images once that happens.  Once that is successfully built, we can re-land #274.

**Comment by martinthomson** [comment]
OK, this should be sorted now.
