### ISSUE TITLE
how to add dependancies to go with xml

### ISSUE THREAD

**Issue by mcr** [martinthomson/i-d-template#290]
When using xi:include to insert yang or other things, those things might need to be created.  That can be done with additional dependancies in the top-level Makefile, but how to add it to drafts_source?
I think that adding something like:

     drafts_source := $(join $(drafts),$(draft_types)) ${extra_sources}

to id.mk might work.

**Comment by martinthomson** [comment]
That won't work, sadly, as that variable is used for other purposes.  What you really want is to say which drafts depend on what other material.

If you are using includes in markdown, the module is a dependency of the XML file:
```make
draft-mcr-yang-is-awesome.xml: module.yang
```

Otherwise, with `<xi:include>` you need to make the file a dependency of all of the output files:
```make
draft-mcr-yang-is-awesome.html: module.yang
draft-mcr-yang-is-awesome.txt: module.yang
```
