### ISSUE TITLE
how to switch from xml to md?

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#294]
I started my repo with an xml file, and after one or two commits I switched to markdown.  I now get this error:
```
; g commit .
cat: M: No such file or directory
make: *** No rule to make target `M-tmp2185.md', needed by `M-tmp2185.xml'.  Stop.
Commit refused: documents don't build successfully.
To commit anyway, run "git commit --no-verify"
```

**Comment by martinthomson** [comment]
Hey @richsalz, this looks like a problem the code that parses `git status --porcelain`.  "M" being one of the flags that we are trying to remove from the output.  It shouldn't have anything to do with the rename as it only uses the current state of the repo and index (files staged for a commit).  The rename doesn't appear to have had an effect, so that's OK.

I just checked this on my Mac (which is well out of date in many ways) and I'm getting the same result.  It looks like sed on the Mac is completely bad.  I've a fix that I'll land.

**Comment by richsalz** [comment]
Awesome, thanks.  I had played around with `sed` but was trying to do something about leading spaces.  oh well, glad you found and fixed it. :)
