### ISSUE TITLE
"Fast" setup instructions tweak

### ISSUE THREAD

**Issue by richsalz** [martinthomson/i-d-template#379]
The sample URL:
```
git remote add origin https://github.com/unicorn-wg/unicorn-protocol
```
Should probably be ssh/git based:
```
git remote add origin git@github.com:unicorn-wg/unicorn-protocol.git
```

**Comment by martinthomson** [comment]
I'd be happy to take a PR.

FWIW, I use HTTPS, even if it is bearer-token-based, because I find it more convenient.  Maybe that says something about my operational security practices, but I don't see this as particularly important.

**Comment by richsalz** [comment]
If HTTPS works, close this.  I guess it doesn't for people who use 2FA?  Or maybe my setup is strange.

**Comment by richsalz** [comment]
I also find it doesn't work in gh-pages, see https://github.com/richsalz/tls12-frozen/actions/runs/4875095072/jobs/8696865007#step:7:21
```
git -C /tmp/ghpages79 push -qf https://****@github.com/richsalz/tls12-frozen gh-pages
git -C /tmp/ghpages79 push -qf https://****@github.com/richsalz/tls12-frozen gh-pages
make[1]: *** [lib/ghpages.mk:127: ghpages] Error 1
```

**Comment by martinthomson** [comment]
I can't access your repository settings, but that CI error occurs if the repository is not configured to allow write access from actions.

As for local pushes, that is a potential problem for people using SSH.  That option works in CI, but it should be using the "origin" remote rather than trying to regenerate the full repository location.  Or rather, it should be using `$(shell git remote get-url --push $(GIT_REMOTE))`, because the repository it is operating in is a temporary that is not configured in the same way.  I can fix that for you.
