### ISSUE TITLE
CI build fails with .targets.mk: No such file or directory

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#383]
```
lib/main.mk:21: Forcing rebuild of .targets.mk
lib/main.mk:33: .targets.mk: No such file or directory
```

As this is now happening on multiple repos, I'd love to know what I'm doing wrong and a simple way to fix this.

E.g., 
https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/actions/runs/5079194601/jobs/9124628690?pr=471
https://github.com/ietf-wg-jsonpath/iregexp/actions/runs/5079074223/jobs/9124364460

**Comment by cabo** [comment]
`.targets.mk` is in `.gitignore`, so it indeed needs to be rebuilt for each CI run.
It seems this was put in there by the setup run.

Updating the lib submodule manually fixed the build.  But should I still be doing this?

**Comment by martinthomson** [comment]
Oh, I'm glad you worked something out because this was baffling.  The document image entrypoint makes the targets file directly (the output is confusing, but that's how make operates) so those builds were a head-scratcher.

Updating the submodule is going to be necessary in some cases, but I don't know specifically what shifted to cause this issue.
