### ISSUE TITLE
"push" CI job fails while "pr" CI jobs succeeds

### ISSUE THREAD

**Issue by cabo** [martinthomson/i-d-template#93]
https://github.com/core-wg/coap-tcp-tls/pull/126

I don't understand why the push CI job uses a directory it doesn't seem to create (`/tmp/ghpages1834/abnf-fix/`, where `abnf-fix` is the name of the branch), while the pr CI job just sails through.

**Comment by martinthomson** [comment]
Hmm, this is a combination of bugs.

Firstly, if this were working correctly on my end, BOTH would fail.  The PR build succeeds because travis sets TRAVIS_BRANCH to "master" for the pr and I incorrectly assume that this is the current branch (big error on my part, you are probably getting weird flip-flopping on your editor's copies, for which I apologize). --> c219122c390134e7162d6fa2c3b76e1ee61e4240



The actual error, the superficial one, is that `git rm` is inconsistent between versions and the version I've tested elsewhere (circle-ci, my machine, mac, etc...) is more tolerant of trying to remove files when the directory doesn't exist.  Travis runs old software, and in this case it's acting quite strangely.  The fix there is pretty simple, I hope. --> 687f963f289408e6a169122394571e5a57817ca8
